### ISSUE TITLE
Adding JSON Column Support

### ISSUE THREAD

**Issue by rob-pomelo** [GoogleCloudPlatform/spanner-schema-diff-tool#4]
Hi,

It would be great if JSON column support could be added to this tool.

Thank you for the consideration!

**Comment by rob-pomelo** [comment]
Naively, https://github.com/rob-pomelo/spanner-schema-diff-tool/pull/1 seems to be sufficient.

**Comment by nielm** [comment]
> Naively, [rob-pomelo#1](https://github.com/rob-pomelo/spanner-schema-diff-tool/pull/1) seems to be sufficient.

Yep that looks great - can you add a JSON column to the unit test in [DDLParserTest](https://github.com/GoogleCloudPlatform/spanner-schema-diff-tool/blob/master/src/test/java/com/google/cloud/solutions/spannerddl/parser/DDLParserTest.java) and submit a pull request please!

Thanks for this - I was waiting for the emultator to update their JJT but it seems to be taking them some time!
